routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','DashboardController@dashboard')->name('dashboard');
Route::get('/clients-registered-today','ReportsController@clientsregisteredtoday')->name('clientsregisteredtoday');
Route::get('/sponsors-registered-today','ReportsController@sponsorsregisteredtoday')->name('sponsorsregisteredtoday');
Route::get('/showlclientssetofpayments','ReportsController@showclientssetofpayments')->name('showclientssetofpayments');
Route::get('/client-set-of-payments-history/{id}','ReportsController@clientssetofpaymentshistory')->name('setofpaymentshistory');
Route::get('/clients-balances','ReportsController@balances')->name('balances');
Route::get('/client-payment-history/{id}','ReportsController@paymenthistory')->name('paymenthistory');
Route::resource('clients','ClientsController');
Route::resource('setpayments','SetPaymentsController');
Route::resource('payments','PaymentsController');
Route::resource('stations','StationsController');
Route::resource('sponsors','SponsorsController');
Route::get('/tuition-balance','BalancesController@getTuitionBalance');
Auth::routes();
Route::get('/active', 'ReportsController@active')->name('active');
Route::get('/station-clients/{id}', 'ReportsController@stationClients')->name('station.clients');
Route::get('/station-balances/{id}', 'ReportsController@stationbalances')->name('station.balances');
Route::get('/station-payments/{id}', 'ReportsController@stationpayments')->name('station.payments');
Route::get('/sponsor-clients/{id}', 'ReportsController@sponsorClients')->name('sponsor.clients');
Route::get('/payments-totals', 'ReportsController@paymentTotals')->name('payments.totals');
Route::get('/payments-made-today','ReportsController@paymentsfortoday')->name('paymentsfortoday');
Route::get('/set-of-payments-made-today','ReportsController@todayssetofpayments')->name('todayssetofpayments');
Route::resource('users', 'UsersController');
Route::resource('roles', 'RolesController');
Route::resource('permissions', 'PermissionsController');

app/Sponsor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Sponsor extends Model
{
    protected $table = 'sponsors';

    //relationship between the client and the sponsor
    public function clients()
    {
        return $this->hasMany('App\Client','sponsor_id');
    }

    //function to capitalize the first letter of the names (mutator)
    public function setFirstNameAttribute($value) {
        $this->attributes['firstname'] = ucfirst($value);
    }
    public function setLastNameAttribute($value) {
        $this->attributes['lastname'] = ucfirst($value);
    }
}

app/Http/Controllers/SponsorsController.php
<?php

namespace App\Http\Controllers;

use App\Sponsor;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class SponsorsController extends Controller
{
    public function __construct() {
        $this->middleware('auth'); //you have to be looged in to access this controller
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (Auth::user()->can('show-sponsors'))
        {
            $sponsors = Sponsor::all();
            return view('sponsors.index',compact('sponsors'));
        }
        abort('401');

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (Auth::user()->can('add-sponsor'))
        {
            return view('sponsors.create');
        }
        abort('401');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if (Auth::user()->can('add-sponsor'))
        {
            //Validate data
            $this->validate($request, [
                'firstname'=>'required|max:120|alpha',
                'lastname'=>'required|max:120|alpha',
                'idnumber'=>'required|max:8',
                'gender'=>'required',
                'residence'=>'required|max:120',
                'contact'=>'required|max:15',

            ]);
            $addSponsor = new Sponsor();
            $addSponsor->firstname = $request->firstname;
            $addSponsor->lastname = $request->lastname;
            $addSponsor->idnumber = $request->idnumber;
            $addSponsor->gender = $request->gender;
            $addSponsor->contact = $request->contact;
            $addSponsor->residence = $request->residence;
            $addSponsor->occupation = $request->occupation;

            $addSponsor->save();

            return redirect(route('sponsors.index'))->with('message','A new sponsor has been added');
        }
        abort('401');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (Auth::user()->can('show-sponsor'))
        {
            $sponsorDetails = Sponsor::find($id);

            return view('sponsors.show',compact('sponsorDetails'));
        }
        abort('401');

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (Auth::user()->can('edit-sponsor'))
        {
            $sponsorDetails = Sponsor::find($id);

            $editSponsor = Sponsor::find($id);

            return view('sponsors.edit',compact('editSponsor'));
        }
        abort('401');


    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if (Auth::user()->can('edit-sponsor'))
        {
            //Validate data
            $this->validate($request, [
                'firstname'=>'required|max:120|alpha',
                'lastname'=>'required|max:120|alpha',
                'idnumber'=>'required|max:8',
                'gender'=>'required',
                'residence'=>'required|max:120',
                'contact'=>'required|max:15',

            ]);
            $updateSponsor = Sponsor::find($id);
            $updateSponsor->firstname = $request->firstname;
            $updateSponsor->lastname = $request->lastname;
            $updateSponsor->idnumber = $request->idnumber;
            $updateSponsor->gender = $request->gender;
            $updateSponsor->contact = $request->contact;
            $updateSponsor->residence = $request->residence;
            $updateSponsor->occupation = $request->occupation;

            $updateSponsor->save();
            return redirect(route('sponsors.index'))->with('message','Sponsor details has been updated successfully');
        }
        abort('401');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (Auth::user()->can('delete-sponsor'))
        {
            $deleteSponsor = Sponsor::find($id);
            $deleteSponsor->delete();
            return redirect(route('sponsors.index'))->with('message','Sponsor Deleted Successfully');
        }
        abort('401');

    }
}

resources/views/sponsors/create.blade.php
@extends('layouts.master')
@section('title')
    Sponsor | Add
@endsection
@section('main-content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Add Sponsor
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Add a new sponsor</li>
        </ol>
    </section>

    <!-- Main content -->
    <div class="box">
        <div class="box-body">
            <div class="col-md-6 col-md-offset-3">
            <form action="{{route('sponsors.store')}}" method="post">
                {{csrf_field()}}
                    <div class="form-group row">
                        <label for="firstname" class="col-sm-3 col-form-label">First Name</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" id="firstname" name="firstname" placeholder="First Name"  value="{{ old('firstname') }}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="lastname" class="col-sm-3 col-form-label">Last Name</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" id="lastname" name="lastname" placeholder="Last Name"  value="{{ old('lastname') }}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="idnumber" class="col-sm-3 col-form-label">ID Number</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" id="idnumber" name="idnumber" placeholder="ID Number"  value="{{ old('idnumber') }}">
                        </div>
                    </div>
                    <fieldset class="form-group">
                        <div class="row">
                            <label for="gender" class="col-sm-3 col-form-label">Gender</label>
                            <div class="col-sm-9">
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="gender" id="gender"
                                           value="Male"  {{ old('gender')=="Male" ? 'checked='.'"'.'checked'.'"' : '' }}>
                                    <label class="form-check-label" for="gender" >
                                        Male
                                    </label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="gender" id="gender"
                                           value="Female" {{ old('gender')=="Female" ? 'checked='.'"'.'checked'.'"' : '' }}>
                                    <label class="form-check-label" for="gender">
                                        Female
                                    </label>
                                </div>
                            </div>
                        </div>
                    </fieldset>
                    <div class="form-group row">
                        <label for="contact" class="col-sm-3 col-form-label">Contact</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" id="contact" name="contact" placeholder="Enter Phone Number"  value="{{ old('contact') }}">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="residence" class="col-sm-3 col-form-label">Residence</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" id="residence" name="residence" placeholder="Residence"  value="{{ old('residence') }}">
                        </div>
                    </div>
                <div class="form-group row">
                    <label for="occupation" class="col-sm-3 col-form-label">Occupation</label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" id="occupation" name="occupation" placeholder="Occupation"  value="{{ old('occupation') }}">
                    </div>
                </div>
                    <div class="form-group row">
                        <div class="col-sm-3 col-md-offset-6"><button type="submit" class="btn btn-primary btn-md">Add Sponsor</button></div>
                    </div>
            </form>
            </div>
        </div>

    </div>
    <!-- /.content -->
@endsection

resources/views/sponsors/edit.blade.php
@extends('layouts.master')
@section('title')
    Sponsor | Edit
@endsection
@section('main-content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
           Edit the details of {{$editSponsor->firstname}} {{$editSponsor->lastname}}
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Edit the details of a sponsor</li>
        </ol>
    </section>

    <!-- Main content -->
    <div class="box">
        <div class="box-body">
            <div class="col-md-6 col-md-offset-3">
                <form action="{{route('sponsors.update',$editSponsor->id)}}" method="post">
                    {{csrf_field()}}
                    {!! method_field('PUT') !!}
                    <div class="form-group row">
                        <label for="firstname" class="col-sm-3 col-form-label">First Name</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" id="firstname" name="firstname" value="{!!$editSponsor->firstname!!}" >
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="lastname" class="col-sm-3 col-form-label">Last Name</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" id="lastname" name="lastname" value="{!!$editSponsor->lastname!!}" >
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="idnumber" class="col-sm-3 col-form-label">ID Number</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" id="idnumber" name="idnumber" value="{!!$editSponsor->idnumber!!}">
                        </div>
                    </div>
                    <fieldset class="form-group">
                        <div class="row">
                            <label for="gender" class="col-sm-3 col-form-label">Gender</label>
                            <div class="col-sm-9">
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="gender" id="gender"
                                           value="Male"  {{ $editSponsor->gender == 'Male' ? 'checked' : '' }} >
                                    <label class="form-check-label" for="gender" >
                                        Male
                                    </label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="gender" id="gender"
                                           value="Female"  {{ $editSponsor->gender  == 'Female' ? 'checked' : '' }} >
                                    <label class="form-check-label" for="gender">
                                        Female
                                    </label>
                                </div>
                            </div>
                        </div>
                    </fieldset>
                    <div class="form-group row">
                        <label for="contact" class="col-sm-3 col-form-label">Contact</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" id="contact" name="contact" value="{!!$editSponsor->contact!!}">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="residence" class="col-sm-3 col-form-label">Residence</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" id="residence" name="residence" value="{!!$editSponsor->residence!!}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="occupation" class="col-sm-3 col-form-label">Residence</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" id="occupation" name="occupation" value="{!!$editSponsor->occupation!!}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-3 col-md-offset-6"><button type="submit" class="btn btn-primary btn-md">Save Details</button></div>
                    </div>
                </form>
            </div>
        </div>

    </div>
    <!-- /.content -->
@endsection

resources/views/sponsors/index.blade.php
@extends('layouts.master')
@section('title')
    Sponsors | List
@endsection
@section('main-content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Sponsors List
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Sponsor for all the stations available in the system</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <!-- Small boxes (Stat box) -->
        <div class="row">
            <div class="col-lg-12 col-xs-6">
                <!-- /.box -->

                <div class="box">
                    <div class="box-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th class="text-center">S/N</th>
                                <th>First Name</th>
                                <th>Last Name</th>
                                <th>ID Number</th>
                                <th>Gender</th>
                                <th>Residence</th>
                                <th>Contact</th>
                                <th>Occupation</th>
                                <th>Date Added</th>
                                <th>Action</th>
                                <th>Clients</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($sponsors as $sponsor)
                            <tr>
                                <td class="text-center">{{ $loop->index + 1 }}</td>
                                <td><a href="{{route('sponsors.show',$sponsor->id)}}">{!! $sponsor->firstname !!}</a></td>
                                <td><a href="{{route('sponsors.show',$sponsor->id)}}">{!! $sponsor->lastname !!}</a></td>
                                <td>{!! $sponsor->idnumber !!}</td>
                                <td>{!! $sponsor->gender !!}</td>
                                <td>{!! $sponsor->residence !!}</td>
                                <td>{!! $sponsor->contact !!}</td>
                                <td>{!! $sponsor->occupation !!}</td>
                                <td>{!! $sponsor->created_at !!}</td>
                                <td> @if(auth()->user()->can('edit-sponsor'))
                                    <a href="{{ route('sponsors.edit',$sponsor->id) }}"><span class="glyphicon glyphicon-edit" style="margin-right: 8px;"></span></a>
                                    @endif
                                    @if(auth()->user()->can('delete-sponsor'))
                                        <a data-toggle="modal" data-target="#modal-danger-{{$sponsor->id}}"><span class="glyphicon glyphicon-trash "></span></a>
                                    @endif
                                        <div class="modal modal-danger fade" id="modal-danger-{{$sponsor->id}}">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span></button>
                                                    <h4 class="modal-title">Delete?</h4>
                                                </div>
                                                <div class="modal-body">
                                                    <p>Are you sure you want to permanently delete {!! $sponsor->firstname !!} {!! $sponsor->lastname !!}?</p>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-outline pull-left" data-dismiss="modal" onclick="event.preventDefault();">No</button>
                                                    <button type="button" class="btn btn-outline" onclick="
                                                            document.getElementById('delete-form-{{ $sponsor->id }}').submit();
                                                            ">Yes</button>
                                                </div>
                                            </div>
                                            <!-- /.modal-content -->
                                        </div>
                                        <!-- /.modal-dialog -->
                                        <form id="delete-form-{{ $sponsor->id }}" method="post"
                                              action="{{ route('sponsors.destroy',$sponsor->id) }}" style="display: none">
                                            {{ csrf_field() }}
                                            {{ method_field('DELETE') }}
                                        </form>
                                    </div>

                                </td>
                                <td>
                                        <a href="{!! route('sponsor.clients',$sponsor->id) !!}" class="btn btn-block btn-info btn-sm">Clients</a>
                                </td>
                            </tr>
                            @endforeach
                            </tbody>
                            <tfoot>
                            <tr>
                                <th class="text-center">S/N</th>
                                <th>First Name</th>
                                <th>Last Name</th>
                                <th>ID Number</th>
                                <th>Gender</th>
                                <th>Residence</th>
                                <th>Contact</th>
                                <th>Occupation</th>
                                <th>Date Added</th>
                                <th>Action</th>
                                <th>Clients</th>
                            </tr>
                            </tfoot>
                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
        </div>
        <!-- /.row -->
        <!-- /.modal -->

        <div class="modal modal-danger fade" id="modal-danger">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title">Danger Modal</h4>
                    </div>
                    <div class="modal-body">
                        <p>One fine body&hellip;</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-outline">Save changes</button>
                    </div>
                </div>
                <!-- /.modal-content -->
            </div>
            <!-- /.modal-dialog -->
        </div>
        <!-- /.modal -->
    </section>
    <!-- /.content -->
@endsection