routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','DashboardController@dashboard')->name('dashboard');
Route::get('/clients-registered-today','ReportsController@clientsregisteredtoday')->name('clientsregisteredtoday');
Route::get('/sponsors-registered-today','ReportsController@sponsorsregisteredtoday')->name('sponsorsregisteredtoday');
Route::get('/showlclientssetofpayments','ReportsController@showclientssetofpayments')->name('showclientssetofpayments');
Route::get('/client-set-of-payments-history/{id}','ReportsController@clientssetofpaymentshistory')->name('setofpaymentshistory');
Route::get('/clients-balances','ReportsController@balances')->name('balances');
Route::get('/client-payment-history/{id}','ReportsController@paymenthistory')->name('paymenthistory');
Route::resource('clients','ClientsController');
Route::resource('setpayments','SetPaymentsController');
Route::resource('payments','PaymentsController');
Route::resource('stations','StationsController');
Route::resource('sponsors','SponsorsController');
Route::get('/tuition-balance','BalancesController@getTuitionBalance');
Auth::routes();
Route::get('/active', 'ReportsController@active')->name('active');
Route::get('/station-clients/{id}', 'ReportsController@stationClients')->name('station.clients');
Route::get('/station-balances/{id}', 'ReportsController@stationbalances')->name('station.balances');
Route::get('/station-payments/{id}', 'ReportsController@stationpayments')->name('station.payments');
Route::get('/sponsor-clients/{id}', 'ReportsController@sponsorClients')->name('sponsor.clients');
Route::get('/payments-totals', 'ReportsController@paymentTotals')->name('payments.totals');
Route::get('/payments-made-today','ReportsController@paymentsfortoday')->name('paymentsfortoday');
Route::get('/set-of-payments-made-today','ReportsController@todayssetofpayments')->name('todayssetofpayments');
Route::resource('users', 'UsersController');
Route::resource('roles', 'RolesController');
Route::resource('permissions', 'PermissionsController');

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    public function payments()
    {
        return $this->hasMany('App\Payment','client_id');
    }
    public function setpayments()
    {
        return $this->hasMany('App\SetPayment','client_id');
    }

    // this is a recommended way to declare event handlers
    protected static function boot() {
        parent::boot();
        static::deleting(function($client) { // before delete() method call this
            foreach($client->payments as $payment)
            $payment->delete();

        });

        // the following code is for deleting the set payments for a client whenever he/she is deleted

        static::deleting(function($client) { // before delete() method call this
            foreach($client->setpayments as $setpayment)
                $setpayment->delete();

        });
    }
//inverse of the relationship between the sponsor and the client
    public function sponsor()
    {
        return $this->belongsTo('App\Sponsor');
    }

    //inverse of the relationship between the sponsor and the station
    public function station()
    {
        return $this->belongsTo('App\Station');
    }

    //function to capitalize the first letter of the names (mutator)
    public function setFirstNameAttribute($value) {
        $this->attributes['firstname'] = ucfirst($value);
    }
    public function setLastNameAttribute($value) {
        $this->attributes['lastname'] = ucfirst($value);
    }
}

app/Http/Controllers/ClientsController.php
<?php

namespace App\Http\Controllers;

use App\Client;
use App\Sponsor;
use App\Station;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ClientsController extends Controller
{
    public function __construct() {
        $this->middleware('auth'); //you have to be looged in to access this controller
    }


    //display all the clients from the database

    public function index()
    {
        if (Auth::user()->can('show-clients'))
        {
            $clients = Client::all();
            return view('clients.index',compact('clients'));
        }
        abort('401');

    }

    //loads the add clients page
    public function create()
    {
        if (Auth::user()->can('add-client'))
        {
            $sponsors = Sponsor::all();
            $stations = Station::all();
            return view('clients.create',compact(['sponsors','stations']));
        }
        abort('401');

    }

    //processes the submitted data and saves it to the database
    public function store(Request $request)
    {
        if (Auth::user()->can('add-client'))
        {
            //Validate data
            $this->validate($request, [
                'sponsor_id'=>'required',
                'station_id'=>'required',
                'firstname'=>'required|max:120|alpha',
                'lastname'=>'required|max:120|alpha',
                'dateofbirth'=>'required|max:120|date',
                'gender'=>'required|max:120|alpha',
                'residence'=>'required|max:120',
                'medicalhistory'=>'required',

            ]);
            $addclient = new Client();
            $addclient->sponsor_id = $request->sponsor_id;
            $addclient->station_id = $request->station_id;
            $addclient->firstname = $request->firstname;
            $addclient->lastname = $request->lastname;
            $addclient->idnumber = $request->idnumber;
            $addclient->dateofbirth = $request->dateofbirth;
            $addclient->gender = $request->gender;
            $addclient->contact = $request->contact;
            $addclient->residence = $request->residence;
            $addclient->medicalhistory = $request->medicalhistory;
            $addclient->expectedexitdate = $request->expectedexitdate;
            $addclient->exitdate = $request->exitdate;
            $addclient->exitcomments = $request->exitcomments;

            $addclient->save();
            return redirect(route('clients.index'))->with('message','Client Added Successfully');
        }
        abort('401');

    }

    /**
     * //Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (Auth::user()->can('show-client'))
        {
            $clientDetails = Client::find($id);
            return view('clients.show',compact('clientDetails'));
        }
        abort('401');

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (Auth::user()->can('edit-client'))
        {
            $sponsors = Sponsor::all();
            $stations = Station::all();
            $editDetails = Client::find($id);
            return view('clients.edit',compact(['editDetails','sponsors','stations']));
        }
        abort('401');

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if (Auth::user()->can('edit-client'))
        {
            //Validate data
            $this->validate($request, [
                'sponsor_id'=>'required',
                'station_id'=>'required',
                'firstname'=>'required|max:120|alpha',
                'lastname'=>'required|max:120|alpha',
                'dateofbirth'=>'required|max:120|date',
                'gender'=>'required|max:120|alpha',
                'residence'=>'required|max:120',
                'medicalhistory'=>'required',

            ]);
            $updateClient = Client::find($id);
            $updateClient->sponsor_id = $request->sponsor_id;
            $updateClient->station_id = $request->station_id;
            $updateClient->firstname = $request->firstname;
            $updateClient->lastname = $request->lastname;
            $updateClient->idnumber = $request->idnumber;
            $updateClient->dateofbirth = $request->dateofbirth;
            $updateClient->gender = $request->gender;
            $updateClient->contact = $request->contact;
            $updateClient->residence = $request->residence;
            $updateClient->medicalhistory = $request->medicalhistory;
            $updateClient->expectedexitdate = $request->expectedexitdate;
            $updateClient->exitdate = $request->exitdate;
            $updateClient->exitcomments = $request->exitcomments;

            $updateClient->save();

            return redirect(route('clients.index'))->with('message','Client details updated successfully');
        }
        abort('401');


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (Auth::user()->can('delete-client'))
        {
            $deleteClient = Client::find($id);
            $deleteClient->delete();
            return redirect(route('clients.index'))->with('message','Client deleted successfully ');
        }
        abort('401');

    }
}

resources/views/clients/create.blade.php
@extends('layouts.master')
@section('title')
    Clients | Add
@endsection
@section('main-content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Add Client
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Admit a new client</li>
        </ol>
    </section>

    <!-- Main content -->
    <div class="box">
        <div class="box-body">
            <form action="{{route('clients.store')}}" method="post">
                {{csrf_field()}}
                <div class="col-md-6">
                    <div class="form-group row">
                        <label for="sponsor_id" class="col-sm-3 col-form-label" >Sponsor's ID Number</label>
                        <div class="col-sm-9">
                            <select  class="form-control" name="sponsor_id" id="sponsor_id">
                                <option value="">Select the ID Number of the Sponsor</option>
                                @foreach($sponsors as $sponsor)
                                    <option value="{{$sponsor->id}}"  @if (old('sponsor_id') == $sponsor->id) selected="selected" @endif>{!! $sponsor->idnumber !!}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="station_id" class="col-sm-3 col-form-label">Station</label>
                        <div class="col-sm-9">
                            <select class="form-control" name="station_id" id="station_id">
                                <option value="">Select the station you wish to admit the client</option>
                                @foreach($stations as $station)
                                    <option value="{{$station->id}}" @if (old('station_id') == $station->id) selected="selected" @endif>{!! $station->name !!}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="firstname" class="col-sm-3 col-form-label">First Name</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" id="firstname" name="firstname" placeholder="First Name" value="{{ old('firstname') }}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="lastname" class="col-sm-3 col-form-label">Last Name</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" id="lastname" name="lastname" placeholder="Last Name" value="{{ old('lastname') }}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="idnumber" class="col-sm-3 col-form-label">ID Number</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" id="idnumber" name="idnumber" placeholder="ID Number" value="{{ old('idnumber') }}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="dateofbirth" class="col-sm-3 col-form-label">Date of Birth</label>
                        <div class="col-sm-9">
                            <input type="date" class="form-control" id="dateofbirth" name="dateofbirth" value="{{ old('dateofbirth') }}">
                        </div>
                    </div>
                    <fieldset class="form-group">
                        <div class="row">
                            <label for="gender" class="col-sm-3 col-form-label">Gender</label>
                            <div class="col-sm-9">
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="gender" id="gender"
                                           value="Male"  {{ old('gender')=="Male" ? 'checked='.'"'.'checked'.'"' : '' }}>
                                    <label class="form-check-label" for="gender" >
                                        Male
                                    </label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="gender" id="gender"
                                           value="Female" {{ old('gender')=="Female" ? 'checked='.'"'.'checked'.'"' : '' }}>
                                    <label class="form-check-label" for="gender">
                                        Female
                                    </label>
                                </div>
                            </div>
                        </div>
                    </fieldset>
                    <div class="form-group row">
                        <label for="contact" class="col-sm-3 col-form-label">Contact</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" id="contact" name="contact" placeholder="Enter Phone Number" value="{{ old('contact') }}">
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group row">
                        <label for="residence" class="col-sm-3 col-form-label">Residence</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" id="residence" name="residence" placeholder="Residence" value="{{ old('residence') }}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="medicalhistory" class="col-sm-3 col-form-label">Medical History</label>
                        <div class="col-sm-9">
                            <textarea type="text" class="form-control" id="medicalhistory" name="medicalhistory" placeholder="Medical History" rows="4" >{{old('medicalhistory') }}</textarea>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="expectedexitdate" class="col-sm-3 col-form-label">Expected Exit </label>
                        <div class="col-sm-9">
                            <input type="date" class="form-control" id="expectedexitdate" name="expectedexitdate" placeholder="Expected date of finishing the rehab" value="{{ old('expectedexitdate') }}" >
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="exitdate" class="col-sm-3 col-form-label">Exit Date </label>
                        <div class="col-sm-9">
                            <input type="date" class="form-control" id="exitdate" name="exitdate" placeholder="This is the date that a person is discharged" value="{{ old('exitdate') }}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="exitcomments" class="col-sm-3 col-form-label">Exit Comments</label>
                        <div class="col-sm-9">
                            <textarea type="text" class="form-control" id="exitcomments" name="exitcomments" placeholder="Describe the overall outcome of the whole rehabilitation  process for the client" rows="4" >{{old('exitcomments') }}</textarea>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-3 pull-right"><button type="submit" class="btn btn-primary btn-md">Add Client</button></div>
                    </div>
                </div>
            </form>
        </div>

    </div>
    <!-- /.content -->
@endsection

resources/views/clients/index.blade.php
@extends('layouts.master')
@section('title')
    Clients | List
@endsection
@section('main-content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Clients List
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">This shows all the clients across all the centers</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <!-- Small boxes (Stat box) -->
        <div class="row">
            <div class="col-lg-12 col-xs-6">
                <!-- /.box -->

                <div class="box">
                    <div class="box-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th class="text-center">S/N</th>
                                <th>Adm No</th>
                                <th>First Name</th>
                                <th>First Name</th>
                                <th>ID Number </th>
                                <th>Gender </th>
                                <th>Residence </th>
                                <th>Contact</th>
                                <th>Date Added</th>
                                <th>Action</th>
                                <th>Sponsor</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($clients as $client)
                                <tr>
                                    <td class="text-center">{{ $loop->index + 1 }}</td>
                                    <td>{{$client->id}}</td>
                                    <td><a href="{{route('clients.show',$client->id)}}">{!! $client->firstname !!}</a></td>
                                    <td><a href="{{route('clients.show',$client->id)}}">{!! $client->lastname !!}</a></td>
                                    <td>{!! $client->idnumber !!}</td>
                                    <td>{!! $client->gender !!}</td>
                                    <td>{!! $client->residence !!}</td>
                                    <td>{!! $client->contact !!}</td>
                                    <td>{!! $client->created_at !!}</td>
                                    <td> @if(auth()->user()->can('edit-client'))
                                        <a href="{{ route('clients.edit',$client->id) }}"><span class="glyphicon glyphicon-edit" style="margin-right: 8px;" ></span></a>
                                        @endif
                                        @if(auth()->user()->can('delete-client'))
                                        <a data-toggle="modal" data-target="#modal-danger-{{$client->id}}"><span class="glyphicon glyphicon-trash "></span></a>
                                        @endif
                                            <div class="modal modal-danger fade" id="modal-danger-{{$client->id}}">
                                            <div class="modal-dialog">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                            <span aria-hidden="true">&times;</span></button>
                                                        <h4 class="modal-title">Delete?</h4>
                                                    </div>
                                                    <div class="modal-body">
                                                        <p>Are you sure you want to permanently delete this set of payment?</p>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-outline pull-left" data-dismiss="modal" onclick="event.preventDefault();">No</button>
                                                        <button type="button" class="btn btn-outline" onclick="
                                                                document.getElementById('delete-form-{{ $client->id }}').submit();
                                                                ">Yes</button>
                                                    </div>
                                                </div>
                                                <!-- /.modal-content -->
                                            </div>
                                            <!-- /.modal-dialog -->
                                            <form id="delete-form-{{ $client->id }}" method="post"
                                                  action="{{ route('clients.destroy',$client->id) }}" style="display: none">
                                                {{ csrf_field() }}
                                                {{ method_field('DELETE') }}
                                            </form>
                                        </div>
                                    </td>
                                    <td>
                                            <a href="{!! route('sponsors.show',str_replace(array('[',']','"'),'', $client ->sponsor()->pluck('id'))) !!}" class="btn btn-block btn-info btn-sm">Sponsor</a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                            <tfoot>
                            <tr>
                                <th class="text-center">S/N</th>
                                <th>Adm No</th>
                                <th>First Name</th>
                                <th>ID Number </th>
                                <th>Gender </th>
                                <th>Residence </th>
                                <th>Contact</th>
                                <th>Date Added</th>
                                <th>Action</th>
                            </tr>
                            </tfoot>
                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
@endsection