routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','DashboardController@dashboard')->name('dashboard');
Route::get('/clients-registered-today','ReportsController@clientsregisteredtoday')->name('clientsregisteredtoday');
Route::get('/sponsors-registered-today','ReportsController@sponsorsregisteredtoday')->name('sponsorsregisteredtoday');
Route::get('/showlclientssetofpayments','ReportsController@showclientssetofpayments')->name('showclientssetofpayments');
Route::get('/client-set-of-payments-history/{id}','ReportsController@clientssetofpaymentshistory')->name('setofpaymentshistory');
Route::get('/clients-balances','ReportsController@balances')->name('balances');
Route::get('/client-payment-history/{id}','ReportsController@paymenthistory')->name('paymenthistory');
Route::resource('clients','ClientsController');
Route::resource('setpayments','SetPaymentsController');
Route::resource('payments','PaymentsController');
Route::resource('stations','StationsController');
Route::resource('sponsors','SponsorsController');
Route::get('/tuition-balance','BalancesController@getTuitionBalance');
Auth::routes();
Route::get('/active', 'ReportsController@active')->name('active');
Route::get('/station-clients/{id}', 'ReportsController@stationClients')->name('station.clients');
Route::get('/station-balances/{id}', 'ReportsController@stationbalances')->name('station.balances');
Route::get('/station-payments/{id}', 'ReportsController@stationpayments')->name('station.payments');
Route::get('/sponsor-clients/{id}', 'ReportsController@sponsorClients')->name('sponsor.clients');
Route::get('/payments-totals', 'ReportsController@paymentTotals')->name('payments.totals');
Route::get('/payments-made-today','ReportsController@paymentsfortoday')->name('paymentsfortoday');
Route::get('/set-of-payments-made-today','ReportsController@todayssetofpayments')->name('todayssetofpayments');
Route::resource('users', 'UsersController');
Route::resource('roles', 'RolesController');
Route::resource('permissions', 'PermissionsController');

app/SetPayment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SetPayment extends Model
{
    protected $table = 'set_payments';

    public function client()
    {
        return $this->belongsTo('App\Client');
    }
}

app/Http/Controllers/SetPaymentsController.php
<?php

namespace App\Http\Controllers;

use App\Client;
use App\SetPayment;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class SetPaymentsController extends Controller
{
    public function __construct() {
        $this->middleware('auth'); //you have to be looged in to access this controller
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (Auth::user()->can('show-setofpayments'))
        {
            $setpayments = SetPayment::all();
            return view('setpayments.index',compact('setpayments'));
        }
        abort('401');

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (Auth::user()->can('add-setofpayment'))
        {
            $clients = Client::all();
            return view('setpayments.create',compact('clients'));
        }
        abort('401');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        if (Auth::user()->can('add-setofpayment'))
        {
            //validate data
            $this->validate($request, [
                'client_id'=>'required',
                'tuitionfee'=>'numeric',
                'nursefee'=>'numeric',
                'psychiatristfee'=>'numeric',
                'medicalfee'=>'numeric',
                'screeningfee'=>'numeric',

            ]);
            $addSetPayment = new SetPayment();
            $addSetPayment->client_id = $request->client_id;
            $addSetPayment->tuitionfee = $request->tuitionfee;
            $addSetPayment->nursefee = $request->nursefee;
            $addSetPayment->psychiatristfee = $request->psychiatristfee;
            $addSetPayment->medicalfee = $request->medicalfee;
            $addSetPayment->screeningfee = $request->screeningfee;

            $addSetPayment->save();

            return redirect(route('setpayments.index'))->with('message','A new set of payment has been added');
        }
        abort('401');


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (Auth::user()->can('edit-setofpayment'))
        {
            $editsetpayment = SetPayment::find($id);

            return view('setpayments.edit',compact('editsetpayment'));

        }
        abort('401');

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if (Auth::user()->can('edit-setofpayment'))
        {
            //validate data
            $this->validate($request, [
                'client_id'=>'required',
                'tuitionfee'=>'numeric',
                'nursefee'=>'numeric',
                'psychiatristfee'=>'numeric',
                'medicalfee'=>'numeric',
                'screeningfee'=>'numeric',

            ]);
            $updatesetpayment = SetPayment::find($id);
            $updatesetpayment->client_id = $request->client_id;
            $updatesetpayment->tuitionfee = $request->tuitionfee;
            $updatesetpayment->nursefee = $request->nursefee;
            $updatesetpayment->psychiatristfee = $request->psychiatristfee;
            $updatesetpayment->medicalfee = $request->medicalfee;
            $updatesetpayment->screeningfee = $request->screeningfee;

            $updatesetpayment->save();

            return redirect(route('setpayments.index'))->with('message','A set of payment has been updated successfully');
        }
        abort('401');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (Auth::user()->can('delete-setofpayment'))
        {
            $deletesetpayment = SetPayment::find($id);

            $deletesetpayment->delete();
            return redirect(route('setpayments.index'))->with('message','A set of payment has been deleted');

        }
        abort('401');

    }
}

resources/views/setpayments/create.blade.php
@extends('layouts.master')
@section('title')
    Set Payment | Add
@endsection
@section('main-content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Set A Payment
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Set a payment for a certain client</li>
        </ol>
    </section>

    <!-- Main content -->
    <!-- Horizontal Form -->
    <div class="box box-info">
        <!-- form start -->
        <form class="form-horizontal" action="{!! route('setpayments.store') !!}" method="post">
            {!! csrf_field() !!}
            <div class="box-body">
                <div class="col-md-offset-2">
                    <div class="form-group">
                        <label for="client_id" class="col-sm-2 control-label">Client Adm No</label>
                        <div class="col-sm-6">
                            <select required class="form-control" name="client_id" id="client_id">
                                <option >Select the clients admission number</option>
                                @foreach($clients as $client)
                                    <option value="{{$client->id}}" @if (old('client_id') == $client->id) selected="selected" @endif>{!! $client->id !!} </option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                </div>
                <div class="col-md-offset-2">
                    <div class="form-group">
                        <label for="tuitionfee" class="col-sm-2 control-label">Rehab Fee</label>

                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="tuitionfee" name="tuitionfee" placeholder="Rehabilitation Fee" >
                        </div>
                    </div>
                </div>
                <div class="col-md-offset-2">
                    <div class="form-group">
                        <label for="nursefee" class="col-sm-2 control-label">Nurse Fee</label>

                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="nursefee" name="nursefee" placeholder="Nurse Fee" >
                        </div>
                    </div>
                </div>
                <div class="col-md-offset-2">
                    <div class="form-group">
                        <label for="psychiatristfee" class="col-sm-2 control-label">Psychiatrist Fee</label>

                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="psychiatristfee" name="psychiatristfee" placeholder="Psychiatrist Fee" >
                        </div>
                    </div>
                </div>
                <div class="col-md-offset-2">
                    <div class="form-group">
                        <label for="medicalfee" class="col-sm-2 control-label">Medical Fee</label>

                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="medicalfee" name="medicalfee" placeholder="Medical Fee" >
                        </div>
                    </div>
                </div>
                <div class="col-md-offset-2">
                    <div class="form-group">
                        <label for="screeningfee" class="col-sm-2 control-label">Screening Fee</label>

                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="screeningfee" name="screeningfee" placeholder="Screening Fee" >
                        </div>
                    </div>
                    <div class="col-sm-2 col-md-offset-4">
                        <button type="submit" class="btn btn-block btn-primary">Save</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <!-- /.content-wrapper -->
    <!-- /.content -->
@endsection

resources/views/setpayments/edit.blade.php
@extends('layouts.master')
@section('title')
    Set Payment | Edit
@endsection
@section('main-content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Edit Set Payment
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Edit a set of payment for a certain client</li>
        </ol>
    </section>

    <!-- Main content -->
    <!-- Horizontal Form -->
    <div class="box box-info">
        <!-- form start -->
        <form class="form-horizontal" action="{!! route('setpayments.update',$editsetpayment->id) !!}" method="post">
            {!! csrf_field() !!}
            {{method_field('PUT')}}
            <div class="box-body">
                <div class="col-md-offset-2">
                    <div class="form-group">
                        <label for="client_id" class="col-sm-2 control-label">Client ID</label>

                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="client_id" name="client_id" value="{{$editsetpayment->client_id}}" @if (old('client_id') == $client->id) selected="selected" @endif>
                        </div>
                    </div>
                </div>
                <div class="col-md-offset-2">
                    <div class="form-group">
                        <label for="tuitionfee" class="col-sm-2 control-label">Rehab Fee</label>

                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="tuitionfee" name="tuitionfee" value="{{$editsetpayment->tuitionfee}}">
                        </div>
                    </div>
                </div>
                <div class="col-md-offset-2">
                    <div class="form-group">
                        <label for="nursefee" class="col-sm-2 control-label">Nurse Fee</label>

                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="nursefee" name="nursefee" value="{{$editsetpayment->nursefee}}" >
                        </div>
                    </div>
                </div>
                <div class="col-md-offset-2">
                    <div class="form-group">
                        <label for="psychiatristfee" class="col-sm-2 control-label">Psychiatrist Fee</label>

                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="psychiatristfee" name="psychiatristfee" value="{{$editsetpayment->pychiatristfee}}" >
                        </div>
                    </div>
                </div>
                <div class="col-md-offset-2">
                    <div class="form-group">
                        <label for="medicalfee" class="col-sm-2 control-label">Medical Fee</label>

                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="medicalfee" name="medicalfee" value="{{$editsetpayment->medicalfee}}" >
                        </div>
                    </div>
                </div>
                <div class="col-md-offset-2">
                    <div class="form-group">
                        <label for="screeningfee" class="col-sm-2 control-label">Screening Fee</label>

                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="screeningfee" name="screeningfee" value="{{$editsetpayment->screeningfee}}" >
                        </div>
                    </div>
                    <div class="col-sm-2 col-md-offset-4">
                        <button type="submit" class="btn btn-block btn-primary">Save</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <!-- /.content-wrapper -->
    <!-- /.content -->
@endsection

resources/views/setpayments/index.blade.php
@extends('layouts.master')
@section('title')
    Set | of Payments
@endsection
@section('main-content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Set of Payments
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">This shows the records of the amount that the clients are being charged</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <!-- Small boxes (Stat box) -->
        <div class="row">
            <div class="col-lg-12 col-xs-6">
                <!-- /.box -->

                <div class="box">
                    <div class="box-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th class="text-center">S/N</th>
                                <th>Adm No</th>
                                <th>First Name</th>
                                <th>Last Name</th>
                                <th>Rehab </th>
                                <th>Nurse </th>
                                <th>Psychiatric </th>
                                <th>Medical</th>
                                <th>Screening</th>
                                <th>Date Set</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($setpayments as $setpayment)
                            <tr>
                                <td class="text-center">{{ $loop->index + 1 }}</td>
                                <td>{{str_replace(array('[',']','"'),'', $setpayment ->client()->pluck('id'))}}</td>
                                <td><a href="{!! route('clients.show',str_replace(array('[',']','"'),'', $setpayment ->client()->pluck('id'))) !!}">{{str_replace(array('[',']','"'),'', $setpayment ->client()->pluck('firstname'))}}</a></td>
                                <td><a href="{!! route('clients.show',str_replace(array('[',']','"'),'', $setpayment ->client()->pluck('id'))) !!}">{{str_replace(array('[',']','"'),'', $setpayment ->client()->pluck('lastname'))}}</a></td>
                                <td>{!! $setpayment->tuitionfee !!}</td>
                                <td>{!! $setpayment->nursefee !!}</td>
                                <td>{!! $setpayment->psychiatristfee !!}</td>
                                <td>{!! $setpayment->medicalfee !!}</td>
                                <td>{!! $setpayment->screeningfee !!}</td>
                                <td>{!! $setpayment->created_at !!}</td>
                                <td> @if(auth()->user()->can('edit-setofpayment'))
                                    <a href="{{ route('setpayments.edit',$setpayment->id) }}"><span class="glyphicon glyphicon-edit" style="margin-right: 8px;"></span></a>
                                    @endif
                                    @if(auth()->user()->can('delete-setofpayment'))
                                        <a data-toggle="modal" data-target="#modal-danger-{{$setpayment->id}}"><span class="glyphicon glyphicon-trash "></span></a>
                                    @endif
                                        <div class="modal modal-danger fade" id="modal-danger-{{$setpayment->id}}">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span></button>
                                                    <h4 class="modal-title">Delete?</h4>
                                                </div>
                                                <div class="modal-body">
                                                    <p>Are you sure you want to permanently delete this set of payment?</p>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-outline pull-left" data-dismiss="modal" onclick="event.preventDefault();">No</button>
                                                    <button type="button" class="btn btn-outline" onclick="
                                                            document.getElementById('delete-form-{{ $setpayment->id }}').submit();
                                                            ">Yes</button>
                                                </div>
                                            </div>
                                            <!-- /.modal-content -->
                                        </div>
                                        <!-- /.modal-dialog -->
                                        <form id="delete-form-{{ $setpayment->id }}" method="post"
                                              action="{{ route('setpayments.destroy',$setpayment->id) }}" style="display: none">
                                            {{ csrf_field() }}
                                            {{ method_field('DELETE') }}
                                        </form>
                                    </div>
                                </td>
                                </td>
                            </tr>
                            @endforeach
                            </tbody>
                            <tfoot>
                            <tr>
                                <th class="text-center">S/N</th>
                                <th>Adm No</th>
                                <th>First Name</th>
                                <th>Last Name</th>
                                <th>Rehab </th>
                                <th>Nurse </th>
                                <th>Psychiatric </th>
                                <th>Medical</th>
                                <th>Screening</th>
                                <th>Date Set</th>
                                <th>Action</th>
                            </tr>
                            </tfoot>
                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
        </div>
        <!-- /.row -->
        <!-- /.modal -->

        <div class="modal modal-danger fade" id="modal-danger">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title">Danger Modal</h4>
                    </div>
                    <div class="modal-body">
                        <p>One fine body&hellip;</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-outline">Save changes</button>
                    </div>
                </div>
                <!-- /.modal-content -->
            </div>
            <!-- /.modal-dialog -->
        </div>
        <!-- /.modal -->
    </section>
    <!-- /.content -->
@endsection