routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','DashboardController@dashboard')->name('dashboard');
Route::get('/clients-registered-today','ReportsController@clientsregisteredtoday')->name('clientsregisteredtoday');
Route::get('/sponsors-registered-today','ReportsController@sponsorsregisteredtoday')->name('sponsorsregisteredtoday');
Route::get('/showlclientssetofpayments','ReportsController@showclientssetofpayments')->name('showclientssetofpayments');
Route::get('/client-set-of-payments-history/{id}','ReportsController@clientssetofpaymentshistory')->name('setofpaymentshistory');
Route::get('/clients-balances','ReportsController@balances')->name('balances');
Route::get('/client-payment-history/{id}','ReportsController@paymenthistory')->name('paymenthistory');
Route::resource('clients','ClientsController');
Route::resource('setpayments','SetPaymentsController');
Route::resource('payments','PaymentsController');
Route::resource('stations','StationsController');
Route::resource('sponsors','SponsorsController');
Route::get('/tuition-balance','BalancesController@getTuitionBalance');
Auth::routes();
Route::get('/active', 'ReportsController@active')->name('active');
Route::get('/station-clients/{id}', 'ReportsController@stationClients')->name('station.clients');
Route::get('/station-balances/{id}', 'ReportsController@stationbalances')->name('station.balances');
Route::get('/station-payments/{id}', 'ReportsController@stationpayments')->name('station.payments');
Route::get('/sponsor-clients/{id}', 'ReportsController@sponsorClients')->name('sponsor.clients');
Route::get('/payments-totals', 'ReportsController@paymentTotals')->name('payments.totals');
Route::get('/payments-made-today','ReportsController@paymentsfortoday')->name('paymentsfortoday');
Route::get('/set-of-payments-made-today','ReportsController@todayssetofpayments')->name('todayssetofpayments');
Route::resource('users', 'UsersController');
Route::resource('roles', 'RolesController');
Route::resource('permissions', 'PermissionsController');

app/Payment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Payment extends Model
{
    protected $table = 'payments';

    /**
     * Get the post the name of a certain payment.
     */
    public function client()
    {
        return $this->belongsTo('App\Client','client_id');
    }
}

app/Http/Controllers/PaymentsController.php
<?php

namespace App\Http\Controllers;
use App\Client;
use Illuminate\Http\Request;
use App\Payment;
use Illuminate\Support\Facades\Auth;

class PaymentsController extends Controller
{
    public function __construct() {
        $this->middleware('auth'); //you have to be looged in to access this controller
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (Auth::user()->can('show-payments'))
        {
            $payments = Payment::all();
            return view('payments.index',compact('payments'));
        }
        abort('401');

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (Auth::user()->can('add-payment'))
        {
            $clients = Client::all();
            return view('payments.create',compact('clients'));
        }
        abort('401');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if (Auth::user()->can('add-payment'))
        {
            //validate data
            $this->validate($request, [
                'client_id'=>'required',
                'tuitionfee'=>'numeric',
                'nursefee'=>'numeric',
                'psychiatristfee'=>'numeric',
                'medicalfee'=>'numeric',
                'screeningfee'=>'numeric',

            ]);
            $pay = new Payment();
            $pay->client_id = $request->client_id;
            $pay->tuitionfee = $request->tuitionfee;
            $pay->nursefee = $request->nursefee;
            $pay->psychiatristfee = $request->psychiatristfee;
            $pay->medicalfee = $request->medicalfee;
            $pay->screeningfee = $request->screeningfee;

            $pay->save();

            return redirect(route('payments.index'))->with('message','A new payment has been added');
        }
        abort('401');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (Auth::user()->can('show-payment'))
        {
            $paymentDetails = Payment::find($id);
            return view('payments.show',compact('paymentDetails'));
        }
        abort('401');

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (Auth::user()->can('edit-payment'))
        {
            $editPayment = Payment::find($id);
            $clients = Client::all();
            return view('payments.edit',compact(['editPayment','clients']));
        }
        abort('401');


    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if (Auth::user()->can('edit-payment'))
        {
            //validate data
            $this->validate($request, [
                'client_id'=>'required',
                'tuitionfee'=>'numeric',
                'nursefee'=>'numeric',
                'psychiatristfee'=>'numeric',
                'medicalfee'=>'numeric',
                'screeningfee'=>'numeric',

            ]);
            $updatePayment = Payment::find($id);
            $updatePayment->tuitionfee = $request ->tuitionfee;
            $updatePayment->nursefee = $request->nursefee;
            $updatePayment->psychiatristfee = $request->psychiatristfee;
            $updatePayment->medicalfee = $request->medicalfee;
            $updatePayment->screeningfee = $request->screeningfee;

            $updatePayment->save();

            return redirect(route('payments.index'))->with('message','Payment has been updated successfully');
        }
        abort('401');


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (Auth::user()->can('delete-payment'))
        {
            $deletePayment = Payment::find($id);
            $deletePayment->delete();

            return redirect(route('payments.index'))->with('message','Payment Deleted Successfully');
        }
        abort('401');

    }
}

resources/views/payments/create.blade.php
@extends('layouts.master')
@section('title')
    Payment | Add
@endsection
@section('main-content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Pay
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Make a payment for  the client</li>
        </ol>
    </section>

    <div class="box box-info">
        <!-- form start -->
        <form class="form-horizontal" action="{!! route('payments.store') !!}" method="post">
            {!! csrf_field() !!}
            <div class="box-body">
                <div class="col-md-offset-2">
                    <div class="form-group">
                        <label for="client_id" class="col-sm-2 control-label">Client Adm No</label>
                        <div class="col-sm-6">
                            <select required class="form-control" name="client_id" id="client_id">
                                <option >Select the clients admission number</option>
                                @foreach($clients as $client)
                                    <option value="{{$client->id}}" @if (old('client_id') == $client->id) selected="selected" @endif>{!! $client->id !!} </option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                </div>
                <div class="col-md-offset-2">
                    <div class="form-group">
                        <label for="tuitionfee" class="col-sm-2 control-label">Rehab Fee</label>

                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="tuitionfee" name="tuitionfee" placeholder="Rehabilitation Fee" >
                        </div>
                    </div>
                </div>
                <div class="col-md-offset-2">
                    <div class="form-group">
                        <label for="nursefee" class="col-sm-2 control-label">Nurse Fee</label>

                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="nursefee" name="nursefee" placeholder="Nurse Fee" >
                        </div>
                    </div>
                </div>
                <div class="col-md-offset-2">
                    <div class="form-group">
                        <label for="psychiatristfee" class="col-sm-2 control-label">Psychiatrist Fee</label>

                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="psychiatristfee" name="psychiatristfee" placeholder="Psychiatrist Fee" >
                        </div>
                    </div>
                </div>
                <div class="col-md-offset-2">
                    <div class="form-group">
                        <label for="medicalfee" class="col-sm-2 control-label">Medical Fee</label>

                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="medicalfee" name="medicalfee" placeholder="Medical Fee" >
                        </div>
                    </div>
                </div>
                <div class="col-md-offset-2">
                    <div class="form-group">
                        <label for="screeningfee" class="col-sm-2 control-label">Screening Fee</label>

                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="screeningfee" name="screeningfee" placeholder="Screening Fee" >
                        </div>
                    </div>
                    <div class="col-sm-2 col-md-offset-4">
                        <button type="submit" class="btn btn-block btn-primary">Save</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <!-- /.content-wrapper -->
    <!-- /.content -->
@endsection

resources/views/payments/edit.blade.php
@extends('layouts.master')
@section('title')
    Payment | Edit
@endsection
@section('main-content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Edit a Payment
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Edit a payment for a certain client</li>
        </ol>
    </section>

    <!-- Main content -->
    <!-- Horizontal Form -->
    <div class="box box-info">
        <!-- form start -->
        <form class="form-horizontal" action="{!! route('payments.update',$editPayment->id) !!}" method="post">
            {!! csrf_field() !!}
            {{method_field('PUT')}}
            <div class="box-body">
                <div class="col-md-offset-2">
                    <div class="form-group">
                        <label for="client_id" class="col-sm-2 control-label">Client Adm No</label>
                        <div class="col-sm-6">
                            <select required class="form-control" name="client_id" id="client_id">
                                <option >{!! $editPayment->client_id !!}</option>
                                @foreach($clients as $client)
                                    <option value="{{$client->id}}" @if (old('client_id') == $client->id) selected="selected" @endif>{!! $client->id !!} </option>
                                @endforeach
                            </select>
                        </div>
                </div>
                <div class="col-md-offset-2">
                    <div class="form-group">
                        <label for="tuitionfee" class="col-sm-2 control-label">Rehab Fee</label>

                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="tuitionfee" name="tuitionfee" value="{{$editPayment->tuitionfee}}">
                        </div>
                    </div>
                </div>
                <div class="col-md-offset-2">
                    <div class="form-group">
                        <label for="nursefee" class="col-sm-2 control-label">Nurse Fee</label>

                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="nursefee" name="nursefee" value="{{$editPayment->nursefee}}" >
                        </div>
                    </div>
                </div>
                <div class="col-md-offset-2">
                    <div class="form-group">
                        <label for="psychiatristfee" class="col-sm-2 control-label">Psychiatrist Fee</label>

                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="psychiatristfee" name="psychiatristfee" value="{{$editPayment->pychiatristfee}}" >
                        </div>
                    </div>
                </div>
                <div class="col-md-offset-2">
                    <div class="form-group">
                        <label for="medicalfee" class="col-sm-2 control-label">Medical Fee</label>

                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="medicalfee" name="medicalfee" value="{{$editPayment->medicalfee}}" >
                        </div>
                    </div>
                </div>
                <div class="col-md-offset-2">
                    <div class="form-group">
                        <label for="screeningfee" class="col-sm-2 control-label">Screening Fee</label>

                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="screeningfee" name="screeningfee" value="{{$editPayment->screeningfee}}" >
                        </div>
                    </div>
                    <div class="col-sm-2 col-md-offset-4">
                        <button type="submit" class="btn btn-block btn-primary">Save Changes</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <!-- /.content-wrapper -->
    <!-- /.content -->
@endsection

resources/views/payments/index.blade.php
@extends('layouts.master')
@section('title')
    Payments | List
@endsection
@section('main-content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            List of Payments
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">This shows the records of the amount that the clients have been paying</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <!-- Small boxes (Stat box) -->
        <div class="row">
            <div class="col-lg-12 col-xs-6">
                <!-- /.box -->

                <div class="box">
                    <div class="box-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th class="text-center">S/N</th>
                                <th>Adm No</th>
                                <th>First Name</th>
                                <th>Last Name</th>
                                <th>Rehab </th>
                                <th>Nurse </th>
                                <th>Psychiatric </th>
                                <th>Medical</th>
                                <th>Screening</th>
                                <th>Date Paid</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($payments as $payment)
                                <tr>
                                    <td class="text-center">{{ $loop->index + 1 }}</td>
                                    <td>{{str_replace(array('[',']','"'),'', $payment ->client()->pluck('id'))}}</td>
                                    <td><a href="{!! route('clients.show',str_replace(array('[',']','"'),'', $payment ->client()->pluck('id'))) !!}">{{str_replace(array('[',']','"'),'', $payment ->client()->pluck('firstname'))}}</a></td>
                                    <td><a href="{!! route('clients.show',str_replace(array('[',']','"'),'', $payment ->client()->pluck('id'))) !!}">{{str_replace(array('[',']','"'),'', $payment ->client()->pluck('lastname'))}}</a></td>
                                    <td>{!! $payment->tuitionfee !!}</td>
                                    <td>{!! $payment->nursefee !!}</td>
                                    <td>{!! $payment->psychiatristfee !!}</td>
                                    <td>{!! $payment->medicalfee !!}</td>
                                    <td>{!! $payment->screeningfee !!}</td>
                                    <td>{!! $payment->created_at !!}</td>
                                    <td> @if(auth()->user()->can('edit-payment'))
                                        <a href="{{ route('payments.edit',$payment->id) }}"><span class="glyphicon glyphicon-edit" style="margin-right: 8px;"></span></a>
                                        @endif
                                        @if(auth()->user()->can('delete-payment'))
                                            <a data-toggle="modal" data-target="#modal-danger-{{$payment->id}}"><span class="glyphicon glyphicon-trash "></span></a>
                                        @endif
                                            <div class="modal modal-danger fade" id="modal-danger-{{$payment->id}}">
                                            <div class="modal-dialog">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                            <span aria-hidden="true">&times;</span></button>
                                                        <h4 class="modal-title">Delete?</h4>
                                                    </div>
                                                    <div class="modal-body">
                                                        <p>Are you sure you want to permanently delete this set of payment?</p>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-outline pull-left" data-dismiss="modal" onclick="event.preventDefault();">No</button>
                                                        <button type="button" class="btn btn-outline" onclick="
                                                                document.getElementById('delete-form-{{ $payment->id }}').submit();
                                                                ">Yes</button>
                                                    </div>
                                                </div>
                                                <!-- /.modal-content -->
                                            </div>
                                            <!-- /.modal-dialog -->
                                            <form id="delete-form-{{ $payment->id }}" method="post"
                                                  action="{{ route('payments.destroy',$payment->id) }}" style="display: none">
                                                {{ csrf_field() }}
                                                {{ method_field('DELETE') }}
                                            </form>
                                        </div>
                                    </td>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                            <tfoot>
                            <tr>
                                <th class="text-center">S/N</th>
                                <th>Adm No</th>
                                <th>First Name</th>
                                <th>Last Name</th>
                                <th>Rehab </th>
                                <th>Nurse </th>
                                <th>Psychiatric </th>
                                <th>Medical</th>
                                <th>Screening</th>
                                <th>Date Paid</th>
                                <th>Action</th>
                            </tr>
                            </tfoot>
                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
        </div>
        <!-- /.row -->
        <!-- /.modal -->

        <div class="modal modal-danger fade" id="modal-danger">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title">Danger Modal</h4>
                    </div>
                    <div class="modal-body">
                        <p>One fine body&hellip;</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-outline">Save changes</button>
                    </div>
                </div>
                <!-- /.modal-content -->
            </div>
            <!-- /.modal-dialog -->
        </div>
        <!-- /.modal -->
    </section>
    <!-- /.content -->
@endsection